version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./../Dockerfile.frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules


  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      - CELERY_BROKER=redis://redis:16379/0
      - CELERY_BACKEND=redis://redis:16379/0
    env_file:
      - ./cub/.env


  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=cub
      - POSTGRES_USER=cub
      - POSTGRES_PASSWORD=cub
    ports:
      - "15432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/


  redis:
    image: redis:7.2.3
    ports:
      - "16379:6379"

volumes:
  pg_data: